# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 09:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_division', models.CharField(choices=[('STAR', 'Star'), ('THREESTAR', '3 Star'), ('FIVESTAR', '5 Star')], max_length=10)),
                ('unit_price', models.IntegerField()),
                ('valid_till', models.DateField(null=True)),
                ('add_date', models.DateField(default=datetime.datetime(2017, 2, 22, 9, 7, 43, 194337, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=10, null=True)),
                ('barcode', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('add_date', models.DateField(default=datetime.datetime(2017, 2, 22, 9, 7, 43, 194337, tzinfo=utc))),
                ('active', models.BooleanField(default=True)),
                ('cost_price', models.IntegerField()),
                ('discount_allowed', models.BooleanField(default=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainusers.Producer')),
            ],
        ),
        migrations.AddField(
            model_name='pricelist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='pricelist',
            unique_together=set([('product', 'class_division')]),
        ),
    ]
