# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 09:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('short_code', models.CharField(default='SCD', max_length=10)),
                ('contact', models.IntegerField()),
                ('email', models.CharField(max_length=50, null=True)),
                ('address1', models.CharField(max_length=200, null=True)),
                ('address2', models.CharField(max_length=200, null=True)),
                ('pin', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateField(default=datetime.datetime(2017, 2, 22, 9, 7, 43, 194337, tzinfo=utc))),
                ('class_division', models.CharField(choices=[('STAR', 'Star'), ('THREESTAR', '3 Star'), ('FIVESTAR', '5 Star')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('short_code', models.CharField(default='SCD', max_length=10)),
                ('contact', models.IntegerField()),
                ('email', models.CharField(max_length=50, null=True)),
                ('address1', models.CharField(max_length=200, null=True)),
                ('address2', models.CharField(max_length=200, null=True)),
                ('pin', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateField(default=datetime.datetime(2017, 2, 22, 9, 7, 43, 194337, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Retail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('short_code', models.CharField(default='SCD', max_length=10)),
                ('contact', models.IntegerField()),
                ('email', models.CharField(max_length=50, null=True)),
                ('address1', models.CharField(max_length=200, null=True)),
                ('address2', models.CharField(max_length=200, null=True)),
                ('pin', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateField(default=datetime.datetime(2017, 2, 22, 9, 7, 43, 194337, tzinfo=utc))),
            ],
        ),
    ]
